### ISSUE TITLE
Errors downloading avatar

### ISSUE THREAD

**Issue by jgarrettvml** [RobeSantoro/ReadyPlayerMe-Blender-Tools#1]
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ReadyPlayerMe-Blender-Tools\RPM_API_Request.py", line 204, in execute
    rename_armature(context, url_params_list)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ReadyPlayerMe-Blender-Tools\RPM_API_Request.py", line 44, in rename_armature
    context.object.name = context.scene.RPM.avatar_name + '_' + '_'.join(postfix)
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by RobeSantoro** [comment]
Hi Josh, thanks for checking the addon; debugging this error seems pretty simple.
I just need the time to do it...

Please describe all the steps you took to have this error
